#include "ClassiCube/src/Commands.h"

extern struct ChatCommand AbortCommand;
extern struct ChatCommand AscendCommand;
extern struct ChatCommand CenterCommand;
extern struct ChatCommand CheckoutCommand;
extern struct ChatCommand CircleCommand;
extern struct ChatCommand CopyCommand;
extern struct ChatCommand CutCommand;
extern struct ChatCommand DescendCommand;
extern struct ChatCommand EarlierCommand;
extern struct ChatCommand EnvironmentCommand;
extern struct ChatCommand FillCommand;
extern struct ChatCommand FixGrassCommand;
extern struct ChatCommand FlipCommand;
extern struct ChatCommand HelpBrushCommand;
extern struct ChatCommand LaterCommand;
extern struct ChatCommand LineCommand;
extern struct ChatCommand MapInfoCommand;
extern struct ChatCommand MarkAllCommand;
extern struct ChatCommand MarkCommand;
extern struct ChatCommand MeasureCommand;
extern struct ChatCommand OutlineCommand;
extern struct ChatCommand PaintCommand;
extern struct ChatCommand PasteCommand;
extern struct ChatCommand PicoCommand;
extern struct ChatCommand PlaceCommand;
extern struct ChatCommand PyramidCommand;
extern struct ChatCommand ReachDistanceCommand;
extern struct ChatCommand RedoCommand;
extern struct ChatCommand ReplaceAllCommand;
extern struct ChatCommand ReplaceCommand;
extern struct ChatCommand ReplaceNotCommand;
extern struct ChatCommand RotateCommand;
extern struct ChatCommand SmoothCommand;
extern struct ChatCommand SpeedCommand;
extern struct ChatCommand SphereCommand;
extern struct ChatCommand TimeCommand;
extern struct ChatCommand TreeCommand;
extern struct ChatCommand TriangleCommand;
extern struct ChatCommand UndoCommand;
extern struct ChatCommand UndoListCommand;
extern struct ChatCommand WriteCommand;
extern struct ChatCommand ZCommand;

void Commands_RegisterAll(void) {
    Commands_Register(&AbortCommand);
    Commands_Register(&AscendCommand);
    Commands_Register(&CenterCommand);
    Commands_Register(&CheckoutCommand);
    Commands_Register(&CircleCommand);
    Commands_Register(&CopyCommand);
    Commands_Register(&CutCommand);
    Commands_Register(&DescendCommand);
    Commands_Register(&EarlierCommand);
    Commands_Register(&EnvironmentCommand);
    Commands_Register(&FillCommand);
    Commands_Register(&FixGrassCommand);
    Commands_Register(&FlipCommand);
    Commands_Register(&HelpBrushCommand);
    Commands_Register(&LaterCommand);
    Commands_Register(&LineCommand);
    Commands_Register(&MapInfoCommand);
    Commands_Register(&MarkAllCommand);
    Commands_Register(&MarkCommand);
    Commands_Register(&MeasureCommand);
    Commands_Register(&OutlineCommand);
    Commands_Register(&PaintCommand);
    Commands_Register(&PasteCommand);
    Commands_Register(&PicoCommand);
    Commands_Register(&PlaceCommand);
    Commands_Register(&PyramidCommand);
    Commands_Register(&ReachDistanceCommand);
    Commands_Register(&RedoCommand);
    Commands_Register(&ReplaceAllCommand);
    Commands_Register(&ReplaceCommand);
    Commands_Register(&ReplaceNotCommand);
    Commands_Register(&RotateCommand);
    Commands_Register(&SmoothCommand);
    Commands_Register(&SpeedCommand);
    Commands_Register(&SphereCommand);
    Commands_Register(&TimeCommand);
    Commands_Register(&TreeCommand);
    Commands_Register(&TriangleCommand);
    Commands_Register(&UndoCommand);
    Commands_Register(&UndoListCommand);
    Commands_Register(&WriteCommand);
    Commands_Register(&ZCommand);
}
